/**
 * Xplore Riyadh — Internationalization (i18n) Module
 * Supports: English (en) and Arabic (ar)
 */
var XploreLang = (function () {
    'use strict';

    var T = {
        en: {
            /* Page titles */
            'title.home':     'Xplore Riyadh – Discover Events & Experiences',
            'title.login':    'Login – Xplore Riyadh',
            'title.register': 'Create Account – Xplore Riyadh',

            /* Navigation */
            'nav.home':        'Home',
            'nav.events':      'Events',
            'nav.restaurants': 'Restaurants & Coffee Shops',
            'nav.sports':      'Esports',
            'nav.about':       'About',
            'nav.contact':     'Contact',
            'nav.login':       'Login',
            'nav.signup':      'Sign Up',
            'nav.profile':     'My Profile',
            'nav.favourites':  'Favourites',
            'nav.bookings':    'My Bookings',
            'nav.signout':     'Sign Out',
            'lang.switch':     'العربية',

            /* Index — Hero */
            'hero.title': 'Welcome to <span>Xplore Riyadh</span>',
            'hero.desc':  "Your ultimate guide to Riyadh's vibrant entertainment scene. Discover events, sports, dining, parks and cultural experiences all in one place. From Riyadh Season concerts to thrilling sports events and cozy cafés – we've got everything Riyadh has to offer.",

            /* Index — About section */
            'about.title': 'Why Choose Xplore Riyadh?',
            'about.1.h3':  '🎉 Complete Coverage',
            'about.1.p':   'From Riyadh Season zones and mega concerts to local café pop-ups and sports championships – we cover every type of experience across the city.',
            'about.2.h3':  '🏆 Real-Time Updates',
            'about.2.p':   'Stay ahead with our live event calendar powered by official sources like GEA and Riyadh Season. Never miss the best shows and festivals.',
            'about.3.h3':  '⭐ Trusted Ratings',
            'about.3.p':   'User reviews and expert ratings help you choose the perfect outing. Real feedback from thousands of Riyadh visitors and locals.',
            'about.4.h3':  '🚀 Vision 2030 Aligned',
            'about.4.p':   "Supporting Saudi Arabia's entertainment revolution. Discover how the Kingdom is transforming into a global tourism destination.",

            /* Login — Left panel */
            'login.headline': 'Explore the <span>Heart</span><br>of Riyadh',
            'login.lp.desc':  'Discover world-class events, restaurants, cafes, and sports curated just for you.',
            'login.f1.title': 'Exclusive Events',
            'login.f1.desc':  'Concerts, festivals and unique experiences',
            'login.f2.title': 'Restaurants and Coffee Shops',
            'login.f2.desc':  'Handpicked dining across the city',
            'login.f3.title': 'Sports and Fitness',
            'login.f3.desc':  'Best courts, gyms and arenas near you',

            /* Login — Right panel */
            'login.back':      'Back to Home',
            'login.badge':     'Secure Login',
            'login.title':     'Welcome <span>Back</span>',
            'login.sub':       'Sign in to your Xplore account to continue',
            'login.google':    'Google',
            'login.apple':     'Apple',
            'login.divider':   'or continue with email',
            'login.email.lbl': 'Email Address',
            'login.email.ph':  'your@email.com',
            'login.pass.lbl':  'Password',
            'login.pass.ph':   'Enter your password',
            'login.remember':  'Remember me',
            'login.forgot':    'Forgot password?',
            'login.btn':       'Sign In',
            'login.noacct':    "Don't have an account?",
            'login.create':    'Create one free →',
            'login.tos':       'By signing in you agree to our',
            'login.terms':     'Terms',
            'login.privacy':   'Privacy Policy',

            /* Register — Left panel */
            'reg.headline':  'Join <span>Xplore</span><br>Riyadh Today',
            'reg.lp.desc':   'Create your free account in seconds and start discovering everything Riyadh has to offer.',
            'reg.s1.title':  'Create Your Account',
            'reg.s1.desc':   'Fill in your details below — it only takes a minute',
            'reg.s2.title':  'Explore Experiences',
            'reg.s2.desc':   'Browse events, restaurants, sports & parks',
            'reg.s3.title':  'Book & Enjoy',
            'reg.s3.desc':   'Save your favourites and book instantly',

            /* Register — Right panel */
            'reg.back':        'Back to Home',
            'reg.badge':       'Free Account',
            'reg.title':       'Create Your <span>Account</span> ✨',
            'reg.sub':         'Join thousands exploring Riyadh with Xplore',
            'reg.fname.lbl':   'First Name',
            'reg.fname.ph':    'Ahmad',
            'reg.lname.lbl':   'Last Name',
            'reg.lname.ph':    'Al-Rashidi',
            'reg.email.lbl':   'Email Address',
            'reg.email.ph':    'your@email.com',
            'reg.pass.lbl':    'Password',
            'reg.pass.ph':     'At least 8 characters',
            'reg.confirm.lbl': 'Confirm Password',
            'reg.confirm.ph':  'Repeat your password',
            'reg.terms.text':  'I agree to the',
            'reg.terms.link':  'Terms of Service',
            'reg.and':         'and',
            'reg.priv.link':   'Privacy Policy',
            'reg.btn':         'Create Account',
            'reg.hasacct':     'Already have an account?',
            'reg.signin':      'Sign in →',

            /* Password strength */
            'strength.label':  'Password strength',
            'strength.prefix': 'Strength: ',
            'strength.weak':   'Weak',
            'strength.fair':   'Fair',
            'strength.good':   'Good',
            'strength.strong': 'Strong',

            /* Alert messages */
            'alert.fill':      'Please fill in all fields.',
            'alert.email':     'Please enter a valid email address.',
            'alert.passlen':   'Password must be at least 8 characters.',
            'alert.passmatch': 'Passwords do not match.',
            'alert.terms':     'You must agree to the Terms of Service.',
            'alert.exists':    'An account with this email already exists.',
            'alert.wrong':     'Incorrect email or password. Please try again.',
            'alert.social':    'Social login requires backend setup.',

            /* Events page */
            'title.events':      'Events – Xplore Riyadh',
            'events.hero.h1':    'Events in Riyadh',
            'events.hero.p':     'Discover amazing events, festivals, water parks, and entertainment destinations across Riyadh. From Riyadh Season zones to thrilling theme parks, explore and book your experience today.',
            'events.modal.book': 'Visit Website',

            /* CoffeeShop page */
            'title.coffee':      'Restaurants & Coffee Shops – Xplore Riyadh',
            'coffee.hero.h1':    'Best Restaurants & Coffee Shops in Riyadh',
            'coffee.hero.p':     'Discover top coffee shops with premium Arabic coffee, lattes, and authentic Riyadh restaurants. Explore ratings, read reviews, reserve your table or order coffee.',
            'coffee.modal.reserve': 'Reserve Table',

            /* Sport page */
            'title.sport':       'Sports Events – Xplore Riyadh',
            'sport.hero.h1':     'Sports Events in Riyadh',
            'sport.hero.p':      'Explore exciting sports events happening in Riyadh. Check event highlights, ratings, and quick descriptions, then book your tickets directly through WeBook.',
            'sport.modal.book':  'Book on WeBook',

            /* About Us page */
            'title.about':       'About Us – Xplore Riyadh',
            'about.page.h1':     'About Xplore Riyadh',
            'about.page.sub':    'Your gateway to Saudi Arabia\'s entertainment revolution. Inspired by Vision 2030, we help you discover the best events, sports, dining, and cultural experiences transforming Riyadh into a global destination.',
            'about.s1.h2':       'Our Story & Vision 2030',
            'about.s1.p':        'Our journey is inspired by Saudi Vision 2030. Before 2016, entertainment options were limited. Today, thanks to the massive transformation led by the Kingdom, Saudi Arabia has become a global hub for tourism and leisure. We created Xplore Riyadh to keep up with this incredible speed of change and help you navigate the thousands of events happening every year.',
            'about.s2.h2':       'The General Entertainment Authority (GEA)',
            'about.s2.p':        'We closely follow the calendar set by the General Entertainment Authority (GEA). The GEA has successfully organized massive seasons like Riyadh Season and Jeddah Season, attracting millions of visitors. Our goal is to organize this information for you in one simple, easy-to-use place.',
            'about.s3.h2':       'Quality of Life Program',
            'about.s3.p':        'We believe in the "Quality of Life" program, a key pillar of Vision 2030. This program aims to improve lifestyles for individuals and families. By listing sports events, art exhibitions, concerts, and more, we encourage everyone to go out, participate, and enjoy life in the Kingdom.',
            'about.s4.h2':       'What You Can Find Here',
            'about.s4.p':        'We provide accurate details about:',
            'about.s4.l1':       'Mega Seasons:',
            'about.s4.l1t':      'Updates on Riyadh Season, Jeddah Season, and Diriyah Season.',
            'about.s4.l2':       'Concerts:',
            'about.s4.l2t':      'Dates and ticket information for local and international artists.',
            'about.s4.l3':       'Sports:',
            'about.s4.l3t':      'Football matches, Formula 1, boxing championships, and esports.',
            'about.s4.l4':       'Dining:',
            'about.s4.l4t':      'Luxury restaurants, pop-up cafés, and culinary experiences.',
            'about.s5.h2':       'Why This Matters',
            'about.s5.p':        'The entertainment sector creates jobs for Saudi youth and boosts the economy. By using Xplore Riyadh, you\'re supporting this growth while discovering the hidden gems of our beautiful country.',
            'about.s6.h2':       'Ready to Connect?',
            'about.s6.p':        'We\'re always looking to improve. Have suggestions or partnership ideas? Visit our Contact page.',
            'about.contact.link':'Visit our Contact page',

            /* Contact page */
            'title.contact':     'Contact Us – Xplore Riyadh',
            'contact.hero.h1':   'Get In Touch',
            'contact.hero.p':    'We\'d love to hear from you! Whether you have questions about events, partnership opportunities, or feedback about our platform, our team is ready to assist.',
            'contact.info.h2':   'Visit Us',
            'contact.form.h2':   'Send Message',
            'contact.form.name': 'Your Name *',
            'contact.form.email':'Your Email *',
            'contact.form.msg':  'Your Message *',
            'contact.form.btn':  'Send Message',
            'contact.loc.h3':    'Location',
            'contact.loc.p':     'Riyadh, Kingdom of Saudi Arabia',
            'contact.email.h3':  'Email',
            'contact.phone.h3':  'Phone',
            'contact.social.h3': 'Social Media',

            'footer.about_text': 'Your ultimate guide to Riyadh\'s vibrant entertainment scene. Discover events, sports, and cultural experiences.',
            'footer.quick_links':'Quick Links',
            'footer.contact_us': 'Contact Us',
            'footer.location':   'Riyadh, Saudi Arabia',
            'footer.copyright':  '© 2026 Xplore Riyadh. All rights reserved.',

            /* Admin */
            'title.admin':         'Admin Dashboard – Xplore Riyadh',
            'nav.admin':           'Admin',
            'admin.denied.title':  'Access Denied',
            'admin.denied.desc':   'You do not have permission to access the admin panel. An administrator account is required.',
            'admin.denied.back':   'Back to Home',
            'admin.role.sysadmin': 'System Admin',
            'admin.role.admin':    'Admin',
            'admin.role.user':     'User',
            'admin.nav.main':      'Main',
            'admin.nav.overview':  'Overview',
            'admin.nav.usersMgmt': 'User Management',
            'admin.nav.users':     'Users',
            'admin.nav.site':      'Site',
            'admin.page.overview': 'Overview',
            'admin.page.users':    'Trainees & Users Management',
            'admin.stat.total':    'Total Users',
            'admin.stat.regular':  'Regular Users',
            'admin.stat.admins':   'Admins',
            'admin.recent.title':  'Latest Users',
            'admin.recent.viewAll':'View All',
            'admin.users.title':   'User Management',
            'admin.search.ph':     'Search by name or email...',
            'admin.filter.all':    'All Users',
            'admin.filter.user':   'Users Only',
            'admin.filter.admin':  'Admins Only',
            'admin.loading':       'Loading...',
            'admin.empty':         'No users found.',
            'admin.th.name':       'Name',
            'admin.th.email':      'Email',
            'admin.th.phone':      'Phone',
            'admin.th.role':       'Role',
            'admin.th.date':       'Created',
            'admin.th.actions':    'Actions',
            'admin.btn.assign':    'Assign',
            'admin.btn.delete':    'Delete',
            'admin.cantSelf':      'You cannot change your own role',
            'admin.confirm.delete':'Remove this user from the list? (Auth account may remain)',
            'admin.msg.roleOk':    'Role updated successfully',
            'admin.msg.deleted':   'User removed',
            'admin.err.load':      'Failed to load users',
            'admin.err.assign':    'Failed to update role',
            'admin.err.delete':    'Failed to delete user',

            /* Profile */
            'title.profile':       'My Profile – Xplore Riyadh',
            'profile.heading':     'My Profile',
            'profile.lbl.name':    'Full Name',
            'profile.lbl.email':   'Email',
            'profile.lbl.phone':   'Phone',
            'profile.lbl.avatar':  'Avatar image URL',
            'profile.pickAvatar':  'Choose profile photo',
            'profile.removeAvatar':'Remove photo',
            'profile.avatarHint':  'Photo saves automatically and appears in the header',
            'profile.avatarOk':    'Photo updated',
            'profile.avatarRemoved': 'Photo removed',
            'profile.confirmRemoveAvatar': 'Remove your profile photo completely?',
            'profile.lbl.password':'New password',
            'profile.lbl.confirm': 'Confirm password',
            'profile.btn.save':    'Save profile',
            'profile.btn.pass':    'Update password',
            'profile.stats.book':  'Bookings',
            'profile.stats.fav':   'Favorites',
            'profile.saved':       'Profile saved',
            'profile.passOk':      'Password updated',
            'profile.passMismatch':'Passwords do not match',
            'profile.needLogin':   'Please sign in',

            /* Platform & listings */
            'title.bookings':      'My Bookings – Xplore Riyadh',
            'title.favorites':     'Favourites – Xplore Riyadh',
            'platform.detailTitle':'Listing – Xplore Riyadh',
            'platform.stock':      'Tickets left',
            'platform.qty':        'Quantity',
            'platform.buy':        'Buy ticket',
            'platform.backList':   'Back to list',
            'platform.yourRating': 'Your rating',
            'platform.loadErr':    'Could not load data',
            'platform.empty':      'Nothing here yet',
            'platform.badId':      'Missing listing id',
            'platform.notFound':   'Listing not found',
            'platform.loginToFav': 'Sign in to use favourites',
            'platform.loginToBuy': 'Sign in to purchase',
            'platform.loginToRate':'Sign in to rate',
            'platform.favAdded':   'Added to favourites',
            'platform.favRemoved': 'Removed from favourites',
            'platform.buyOk':      'Booking confirmed',
            'platform.buyToastShort': 'Ticket purchased — saved to My bookings',
            'platform.ticketModalTitle': 'Ticket confirmed',
            'platform.ticketBuyer': 'Ticket holder',
            'platform.ticketRef': 'Booking ID',
            'platform.ticketQrLabel': 'Verification code',
            'platform.ticketEvent': 'Experience',
            'platform.ticketQty': 'Quantity',
            'platform.ticketTotal': 'Total',
            'platform.ticketGotoBookings': 'My bookings',
            'platform.ticketClose': 'Close',
            'platform.buyErr':     'Purchase failed',
            'platform.rateThanks': 'Thanks for your rating',
            'platform.err':        'Something went wrong',
            'platform.searchPh':   'Search…',
            'platform.catAll':     'All categories',
            'platform.favBtn':     'Add to favourites',

            'bookings.buyer':      'Ticket holder',
            'bookings.heading':      'My bookings',
            'bookings.empty':      'No bookings yet',
            'bookings.item':       'Experience',
            'bookings.qty':        'Tickets',
            'bookings.total':      'Total',
            'bookings.status':     'Status',
            'bookings.statusOk':   'Confirmed',
            'bookings.statusCancelled': 'Cancelled',
            'bookings.date':       'Purchased',
            'bookings.cancel':     'Cancel booking',
            'bookings.confirmCancel': 'Cancel this booking?',
            'bookings.cancelled':  'Booking cancelled',

            'favorites.heading':   'Favourites',
            'favorites.empty':     'No favourites yet',

            /* Admin platform */
            'admin.nav.platform': 'Platform',
            'admin.nav.listings':  'Listings & tickets',
            'admin.nav.bookings':  'All bookings',
            'admin.nav.stats':     'Sales & stats',
            'admin.listings.title':'Manage listings',
            'admin.listings.add':  'New listing',
            'admin.listings.save': 'Save',
            'admin.listings.edit': 'Edit',
            'admin.listings.del':  'Delete',
            'admin.listings.confirmDel': 'Delete this listing and all linked bookings?',
            'admin.listings.deleted': 'Listing deleted',
            'admin.listings.loaded': 'Loaded into form — edit and save',
            'admin.lst.formNew': 'Add new listing',
            'admin.lst.formEdit': 'Edit listing',
            'admin.lst.formHint': 'Fill all fields then click Save listing',
            'admin.lst.sectionBasic': 'Basic information',
            'admin.lst.sectionPrice': 'Pricing & stock',
            'admin.lst.sectionPlace': 'Location',
            'admin.lst.sectionImage': 'Listing image',
            'admin.lst.type': 'Type',
            'admin.lst.typeHint': 'Event, restaurant, or sport',
            'admin.lst.typeEvent': 'Event',
            'admin.lst.typeRestaurant': 'Restaurant',
            'admin.lst.typeSport': 'Sport',
            'admin.lst.title': 'Title',
            'admin.lst.titlePh': 'e.g. Six Flags Qiddiya',
            'admin.lst.slug': 'Short URL (slug)',
            'admin.lst.slugPh': 'six-flags-qiddiya',
            'admin.lst.slugHint': 'Auto-generated from title if empty',
            'admin.lst.desc': 'Description',
            'admin.lst.descPh': 'Description shown to visitors...',
            'admin.lst.price': 'Price (SAR)',
            'admin.lst.stock': 'Tickets / stock',
            'admin.lst.category': 'Category',
            'admin.lst.categoryPh': 'e.g. Theme parks',
            'admin.lst.venue': 'Venue / city',
            'admin.lst.venuePh': 'e.g. Qiddiya — Riyadh',
            'admin.lst.pickImage': 'Choose image from device',
            'admin.lst.uploading': 'Uploading...',
            'admin.lst.imagePath': 'Image path (URL or local folder)',
            'admin.lst.imagePh': 'event/1.jpeg',
            'admin.lst.imageHint': 'e.g. event/5.jpeg or Supabase URL after upload',
            'admin.lst.noImage': 'No image',
            'admin.lst.published': 'Publish on site (visible to visitors)',
            'admin.lst.publishedShort': 'Published',
            'admin.lst.saveBtn': 'Save listing',
            'admin.lst.listTitle': 'Current listings',
            'admin.lst.thImage': 'Image',
            'admin.lst.errTitle': 'Enter listing title',
            'admin.lst.imageOk': 'Image uploaded',
            'admin.lst.imageLocal': 'Saved local path — place file in site folder',
            'admin.lst.imagePickFirst': 'Choose an image first',
            'admin.lst.imageFail': 'Upload failed',
            'admin.bookings.title':'All bookings',
            'admin.bookings.user': 'User',
            'admin.bookings.remove': 'Remove',
            'admin.bookings.confirmRemove': 'Remove this cancelled booking from the list?',
            'admin.bookings.removed': 'Booking removed',
            'admin.col.actions':   'Actions',
            'admin.stats.title':   'Revenue & top events',
            'admin.stats.revenue': 'Total sales (confirmed)',
            'admin.stats.bookings':'Confirmed bookings count',
            'admin.stats.top':     'Most booked listings'
        },

        ar: {
            /* Page titles */
            'title.home':     'إكسبلور الرياض – اكتشف الفعاليات والتجارب',
            'title.login':    'تسجيل الدخول – إكسبلور الرياض',
            'title.register': 'إنشاء حساب – إكسبلور الرياض',

            /* Navigation */
            'nav.home':        'الرئيسية',
            'nav.events':      'الفعاليات',
            'nav.restaurants': 'المطاعم وكوفيهات',
            'nav.sports':      'الرياضة',
            'nav.about':       'عن الموقع',
            'nav.contact':     'تواصل معنا',
            'nav.login':       'تسجيل الدخول',
            'nav.signup':      'إنشاء حساب',
            'nav.profile':     'ملفي الشخصي',
            'nav.favourites':  'المفضلة',
            'nav.bookings':    'حجوزاتي',
            'nav.signout':     'تسجيل الخروج',
            'lang.switch':     'English',

            /* Index — Hero */
            'hero.title': 'مرحباً بك في <span>إكسبلور الرياض</span>',
            'hero.desc':  'دليلك الشامل لمشهد الترفيه النابض في الرياض. اكتشف الفعاليات والرياضة والمطاعم والحدائق والتجارب الثقافية كلها في مكان واحد. من حفلات موسم الرياض إلى الفعاليات الرياضية المثيرة والمقاهي الدافئة – نوفر لك كل ما تقدمه الرياض.',

            /* Index — About section */
            'about.title': 'لماذا تختار إكسبلور الرياض؟',
            'about.1.h3':  '🎉 تغطية شاملة',
            'about.1.p':   'من مناطق موسم الرياض والحفلات الكبرى إلى المقاهي المحلية وبطولات الرياضة – نغطي كل نوع من التجارب في جميع أنحاء المدينة.',
            'about.2.h3':  '🏆 تحديثات فورية',
            'about.2.p':   'ابقَ في الصدارة مع تقويم الفعاليات المباشر بدعم من مصادر رسمية كهيئة الترفيه وموسم الرياض. لا تفوّت أفضل العروض والمهرجانات.',
            'about.3.h3':  '⭐ تقييمات موثوقة',
            'about.3.p':   'آراء المستخدمين والتقييمات المتخصصة تساعدك على اختيار الخروج المثالي. تغذية راجعة حقيقية من آلاف زوار الرياض والمقيمين.',
            'about.4.h3':  '🚀 متوافق مع رؤية 2030',
            'about.4.p':   'ندعم ثورة الترفيه في المملكة العربية السعودية. اكتشف كيف تتحول المملكة إلى وجهة سياحية عالمية.',

            /* Login — Left panel */
            'login.headline': 'اكتشف <span>قلب</span><br>الرياض',
            'login.lp.desc':  'اكتشف أفضل الفعاليات والمطاعم والمقاهي والرياضة، مختارة خصيصاً لك.',
            'login.f1.title': 'فعاليات حصرية',
            'login.f1.desc':  'حفلات ومهرجانات وتجارب فريدة',
            'login.f2.title': 'مطاعم وكوفيهات',
            'login.f2.desc':  'أفضل أماكن تناول الطعام في المدينة',
            'login.f3.title': 'رياضة ولياقة',
            'login.f3.desc':  'أفضل الملاعب والصالات والمنشآت الرياضية',

            /* Login — Right panel */
            'login.back':      'العودة للرئيسية',
            'login.badge':     'دخول آمن',
            'login.title':     'أهلاً <span>بعودتك</span>',
            'login.sub':       'سجّل دخولك إلى حسابك في إكسبلور للمتابعة',
            'login.google':    'جوجل',
            'login.apple':     'آبل',
            'login.divider':   'أو أدخل بريدك الإلكتروني',
            'login.email.lbl': 'البريد الإلكتروني',
            'login.email.ph':  'بريدك@example.com',
            'login.pass.lbl':  'كلمة المرور',
            'login.pass.ph':   'أدخل كلمة المرور',
            'login.remember':  'تذكّرني',
            'login.forgot':    'نسيت كلمة المرور؟',
            'login.btn':       'تسجيل الدخول',
            'login.noacct':    'ليس لديك حساب؟',
            'login.create':    'أنشئ حساباً مجانياً →',
            'login.tos':       'بتسجيل دخولك فأنت توافق على',
            'login.terms':     'الشروط',
            'login.privacy':   'سياسة الخصوصية',

            /* Register — Left panel */
            'reg.headline':  'انضم إلى <span>إكسبلور</span><br>الرياض اليوم',
            'reg.lp.desc':   'أنشئ حسابك المجاني في ثوانٍ وابدأ باكتشاف كل ما تقدمه الرياض.',
            'reg.s1.title':  'أنشئ حسابك',
            'reg.s1.desc':   'أدخل بياناتك أدناه – لن يستغرق الأمر دقيقة',
            'reg.s2.title':  'استكشف التجارب',
            'reg.s2.desc':   'تصفّح الفعاليات والمطاعم والرياضة والحدائق',
            'reg.s3.title':  'احجز واستمتع',
            'reg.s3.desc':   'احفظ المفضلة واحجز بشكل فوري',

            /* Register — Right panel */
            'reg.back':        'العودة للرئيسية',
            'reg.badge':       'حساب مجاني',
            'reg.title':       'إنشاء <span>حسابك</span> ✨',
            'reg.sub':         'انضم إلى آلاف المستكشفين في الرياض',
            'reg.fname.lbl':   'الاسم الأول',
            'reg.fname.ph':    'أحمد',
            'reg.lname.lbl':   'اسم العائلة',
            'reg.lname.ph':    'الرشيدي',
            'reg.email.lbl':   'البريد الإلكتروني',
            'reg.email.ph':    'بريدك@example.com',
            'reg.pass.lbl':    'كلمة المرور',
            'reg.pass.ph':     '٨ أحرف على الأقل',
            'reg.confirm.lbl': 'تأكيد كلمة المرور',
            'reg.confirm.ph':  'أعد كتابة كلمة المرور',
            'reg.terms.text':  'أوافق على',
            'reg.terms.link':  'شروط الخدمة',
            'reg.and':         'و',
            'reg.priv.link':   'سياسة الخصوصية',
            'reg.btn':         'إنشاء الحساب',
            'reg.hasacct':     'لديك حساب بالفعل؟',
            'reg.signin':      'سجّل دخولك →',

            /* Password strength */
            'strength.label':  'قوة كلمة المرور',
            'strength.prefix': 'القوة: ',
            'strength.weak':   'ضعيفة',
            'strength.fair':   'مقبولة',
            'strength.good':   'جيدة',
            'strength.strong': 'قوية',

            /* Alert messages */
            'alert.fill':      'يرجى ملء جميع الحقول.',
            'alert.email':     'يرجى إدخال بريد إلكتروني صحيح.',
            'alert.passlen':   'كلمة المرور يجب أن تكون 8 أحرف على الأقل.',
            'alert.passmatch': 'كلمتا المرور غير متطابقتين.',
            'alert.terms':     'يجب الموافقة على شروط الخدمة.',
            'alert.exists':    'يوجد حساب مسجل بهذا البريد الإلكتروني.',
            'alert.wrong':     'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
            'alert.social':    'تسجيل الدخول الاجتماعي يتطلب إعداد الخادم.',

            /* Events page */
            'title.events':      'الفعاليات – إكسبلور الرياض',
            'events.hero.h1':    'فعاليات الرياض',
            'events.hero.p':     'اكتشف أروع الفعاليات والمهرجانات والمدن الترفيهية في الرياض. من مناطق موسم الرياض إلى مدن الترفيه المثيرة – استكشف واحجز تجربتك اليوم.',
            'events.modal.book': 'زيارة الموقع',

            /* CoffeeShop page */
            'title.coffee':      'المطاعم وكوفيهات – إكسبلور الرياض',
            'coffee.hero.h1':    'أفضل المطاعم والكوفيهات في الرياض',
            'coffee.hero.p':     'اكتشف أفضل الكوفيهات بقهوتها العربية الأصيلة والمطاعم الراقية في الرياض. استعرض التقييمات واحجز طاولتك الآن.',
            'coffee.modal.reserve': 'احجز طاولة',

            /* Sport page */
            'title.sport':       'الفعاليات الرياضية – إكسبلور الرياض',
            'sport.hero.h1':     'الفعاليات الرياضية في الرياض',
            'sport.hero.p':      'استكشف أبرز الفعاليات الرياضية المثيرة في الرياض. اطّلع على التفاصيل والتقييمات واحجز تذاكرك مباشرةً عبر ويبوك.',
            'sport.modal.book':  'احجز على ويبوك',

            /* About Us page */
            'title.about':       'عن الموقع – إكسبلور الرياض',
            'about.page.h1':     'عن إكسبلور الرياض',
            'about.page.sub':    'بوابتك نحو ثورة الترفيه في المملكة العربية السعودية. مستوحاةً من رؤية 2030، نساعدك على اكتشاف أفضل الفعاليات والرياضة والمطاعم والتجارب الثقافية التي تحوّل الرياض إلى وجهة عالمية.',
            'about.s1.h2':       'قصتنا ورؤية 2030',
            'about.s1.p':        'رحلتنا مستوحاة من رؤية المملكة 2030. قبل عام 2016، كانت خيارات الترفيه محدودة. واليوم، بفضل التحولات الكبرى التي تقودها المملكة، أصبحت المملكة العربية السعودية مركزًا عالميًا للسياحة وأوقات الفراغ. أنشأنا إكسبلور الرياض لنواكب هذه الوتيرة المتسارعة ونساعدك في التنقل بين آلاف الفعاليات سنويًا.',
            'about.s2.h2':       'هيئة الترفيه العامة',
            'about.s2.p':        'نتابع عن كثب التقويم الذي تضعه هيئة الترفيه العامة، التي نظّمت بنجاح مواسم ضخمة كموسم الرياض وموسم جدة، جذبت ملايين الزوار. هدفنا تنظيم هذه المعلومات لك في مكان واحد بسيط وسهل الاستخدام.',
            'about.s3.h2':       'برنامج جودة الحياة',
            'about.s3.p':        'نؤمن ببرنامج "جودة الحياة"، الركيزة الأساسية في رؤية 2030، الذي يهدف إلى تحسين أنماط حياة الأفراد والأسر. من خلال إدراج الفعاليات الرياضية والمعارض الفنية والحفلات وغيرها، نشجع الجميع على الخروج والمشاركة والاستمتاع بالحياة في المملكة.',
            'about.s4.h2':       'ما ستجده هنا',
            'about.s4.p':        'نوفر تفاصيل دقيقة حول:',
            'about.s4.l1':       'المواسم الكبرى:',
            'about.s4.l1t':      'تحديثات موسم الرياض وجدة والدرعية.',
            'about.s4.l2':       'الحفلات:',
            'about.s4.l2t':      'مواعيد وتذاكر الفنانين المحليين والعالميين.',
            'about.s4.l3':       'الرياضة:',
            'about.s4.l3t':      'مباريات كرة القدم، الفورمولا 1، الملاكمة، والرياضات الإلكترونية.',
            'about.s4.l4':       'المطاعم:',
            'about.s4.l4t':      'مطاعم فاخرة ومقاهي مؤقتة وتجارب طهي.',
            'about.s5.h2':       'لماذا هذا مهم؟',
            'about.s5.p':        'يخلق قطاع الترفيه فرص عمل للشباب السعودي ويعزز الاقتصاد. باستخدامك إكسبلور الرياض، تدعم هذا النمو وتكتشف جواهر بلدنا الجميل.',
            'about.s6.h2':       'هل أنت مستعد للتواصل؟',
            'about.s6.p':        'نسعى دائمًا للتحسين. هل لديك اقتراحات أو أفكار لشراكات؟',
            'about.contact.link':'تفضّل بزيارة صفحة التواصل',

            /* Contact page */
            'title.contact':     'تواصل معنا – إكسبلور الرياض',
            'contact.hero.h1':   'تواصل معنا',
            'contact.hero.p':    'يسعدنا سماعك! سواء كانت لديك أسئلة حول الفعاليات، أو فرص شراكة، أو ملاحظات حول منصتنا، فريقنا مستعد لمساعدتك.',
            'contact.info.h2':   'زورنا',
            'contact.form.h2':   'أرسل رسالة',
            'contact.form.name': 'اسمك *',
            'contact.form.email':'بريدك الإلكتروني *',
            'contact.form.msg':  'رسالتك *',
            'contact.form.btn':  'إرسال الرسالة',
            'contact.loc.h3':    'الموقع',
            'contact.loc.p':     'الرياض، المملكة العربية السعودية',
            'contact.email.h3':  'البريد الإلكتروني',
            'contact.phone.h3':  'الهاتف',
            'contact.social.h3': 'وسائل التواصل',

            'footer.about_text': 'دليلك الشامل لمشهد الترفيه في الرياض. اكتشف الفعاليات والرياضة والتجارب الثقافية.',
            'footer.quick_links':'روابط سريعة',
            'footer.contact_us': 'تواصل معنا',
            'footer.location':   'الرياض، المملكة العربية السعودية',
            'footer.copyright':  '© 2026 إكسبلور الرياض. جميع الحقوق محفوظة.',

            /* Admin */
            'title.admin':         'لوحة التحكم – إكسبلور الرياض',
            'nav.admin':           'لوحة التحكم',
            'admin.denied.title':  'غير مصرح',
            'admin.denied.desc':   'ليس لديك صلاحية الوصول إلى لوحة التحكم. يجب أن تكون مشرفاً.',
            'admin.denied.back':   'العودة للرئيسية',
            'admin.role.sysadmin': 'مشرف النظام',
            'admin.role.admin':    'أدمن',
            'admin.role.user':     'مستخدم',
            'admin.nav.main':      'الرئيسية',
            'admin.nav.overview':  'نظرة عامة',
            'admin.nav.usersMgmt': 'إدارة المستخدمين',
            'admin.nav.users':     'المستخدمون',
            'admin.nav.site':      'الموقع',
            'admin.page.overview': 'نظرة عامة',
            'admin.page.users':    'إدارة المتدربين والمستخدمين',
            'admin.stat.total':    'إجمالي المستخدمين',
            'admin.stat.regular':  'المستخدمون',
            'admin.stat.admins':   'المشرفون',
            'admin.recent.title':  'آخر المستخدمين',
            'admin.recent.viewAll':'عرض الكل',
            'admin.users.title':   'إدارة المستخدمين',
            'admin.search.ph':     'بحث بالاسم أو الإيميل...',
            'admin.filter.all':    'كل المستخدمين',
            'admin.filter.user':    'مستخدمون فقط',
            'admin.filter.admin':  'مشرفون فقط',
            'admin.loading':       'جاري التحميل...',
            'admin.empty':         'لا يوجد مستخدمون.',
            'admin.th.name':       'الاسم',
            'admin.th.email':      'البريد الإلكتروني',
            'admin.th.phone':      'رقم الجوال',
            'admin.th.role':       'الدور',
            'admin.th.date':       'تاريخ الإنشاء',
            'admin.th.actions':    'الإجراءات',
            'admin.btn.assign':    'تعيين',
            'admin.btn.delete':    'حذف',
            'admin.cantSelf':      'لا يمكنك تغيير دورك',
            'admin.confirm.delete':'هل تريد حذف هذا المستخدم من القائمة؟',
            'admin.msg.roleOk':    'تم تحديث الدور بنجاح',
            'admin.msg.deleted':   'تم حذف المستخدم',
            'admin.err.load':      'فشل تحميل المستخدمين',
            'admin.err.assign':    'فشل تحديث الدور',
            'admin.err.delete':    'فشل حذف المستخدم',

            'title.profile':       'ملفي الشخصي – إكسبلور الرياض',
            'profile.heading':     'ملفي الشخصي',
            'profile.lbl.name':    'الاسم الكامل',
            'profile.lbl.email':   'البريد الإلكتروني',
            'profile.lbl.phone':   'رقم الجوال',
            'profile.lbl.avatar':  'رابط صورة الملف (اختياري)',
            'profile.pickAvatar':  'اختيار صورة شخصية',
            'profile.removeAvatar':'إزالة الصورة',
            'profile.avatarHint':  'تُحفظ الصورة تلقائياً وتظهر في الوسط وفي الأعلى بجانب اسمك',
            'profile.avatarOk':    'تم تحديث الصورة',
            'profile.avatarRemoved': 'تم إزالة الصورة نهائياً',
            'profile.confirmRemoveAvatar': 'إزالة الصورة الشخصية نهائياً من ملفك والهيدر؟',
            'profile.lbl.password':'كلمة مرور جديدة',
            'profile.lbl.confirm': 'تأكيد كلمة المرور',
            'profile.btn.save':    'حفظ الملف',
            'profile.btn.pass':    'تحديث كلمة المرور',
            'profile.stats.book':  'الحجوزات',
            'profile.stats.fav':   'المفضلة',
            'profile.saved':       'تم حفظ الملف',
            'profile.passOk':      'تم تحديث كلمة المرور',
            'profile.passMismatch':'كلمتا المرور غير متطابقتين',
            'profile.needLogin':   'يرجى تسجيل الدخول',

            'title.bookings':      'حجوزاتي – إكسبلور الرياض',
            'title.favorites':     'المفضلة – إكسبلور الرياض',
            'platform.detailTitle':'العرض – إكسبلور الرياض',
            'platform.stock':      'التذاكر المتبقية',
            'platform.qty':        'الكمية',
            'platform.buy':        'شراء تذكرة',
            'platform.backList':   'رجوع للقائمة',
            'platform.yourRating': 'تقييمك',
            'platform.loadErr':    'تعذر تحميل البيانات',
            'platform.empty':      'لا يوجد محتوى بعد',
            'platform.badId':      'معرّف العرض مفقود',
            'platform.notFound':   'العرض غير موجود',
            'platform.loginToFav': 'سجّل الدخول لاستخدام المفضلة',
            'platform.loginToBuy': 'سجّل الدخول للشراء',
            'platform.loginToRate':'سجّل الدخول للتقييم',
            'platform.favAdded':   'أُضيفت للمفضلة',
            'platform.favRemoved': 'أُزيلت من المفضلة',
            'platform.buyOk':      'تم تأكيد الحجز',
            'platform.buyToastShort': 'تم شراء التذكرة وحفظها في «حجوزاتي»',
            'platform.ticketModalTitle': 'تم شراء التذكرة',
            'platform.ticketBuyer': 'اسم صاحب التذكرة',
            'platform.ticketRef': 'رقم الحجز',
            'platform.ticketQrLabel': 'رمز التحقق (QR)',
            'platform.ticketEvent': 'الفعالية / العرض',
            'platform.ticketQty': 'الكمية',
            'platform.ticketTotal': 'الإجمالي',
            'platform.ticketGotoBookings': 'حجوزاتي',
            'platform.ticketClose': 'إغلاق',
            'platform.buyErr':     'فشل الشراء',
            'platform.rateThanks': 'شكراً لتقييمك',
            'platform.err':        'حدث خطأ',
            'platform.searchPh':   'بحث…',
            'platform.catAll':     'كل التصنيفات',
            'platform.favBtn':     'إضافة للمفضلة',

            'bookings.buyer':      'صاحب التذكرة',
            'bookings.heading':      'حجوزاتي',
            'bookings.empty':      'لا توجد حجوزات بعد',
            'bookings.item':       'تجربة',
            'bookings.qty':        'التذاكر',
            'bookings.total':      'الإجمالي',
            'bookings.status':     'الحالة',
            'bookings.statusOk':   'مؤكد',
            'bookings.statusCancelled': 'ملغى',
            'bookings.date':       'تاريخ الشراء',
            'bookings.cancel':     'إلغاء الحجز',
            'bookings.confirmCancel': 'هل تلغي هذا الحجز؟',
            'bookings.cancelled':  'تم إلغاء الحجز',

            'favorites.heading':     'المفضلة',
            'favorites.empty':       'لا توجد مفضلات بعد',

            'admin.nav.platform': 'المنصة',
            'admin.nav.listings':   'العروض والتذاكر',
            'admin.nav.bookings':   'كل الحجوزات',
            'admin.nav.stats':      'المبيعات والإحصائيات',
            'admin.listings.title': 'إدارة العروض',
            'admin.listings.add':   'عرض جديد',
            'admin.listings.save':  'حفظ',
            'admin.listings.edit':  'تعديل',
            'admin.listings.del':   'حذف',
            'admin.listings.confirmDel': 'حذف هذا العرض وجميع حجوزاته المرتبطة؟',
            'admin.listings.deleted': 'تم حذف العرض',
            'admin.listings.loaded': 'تم تحميل العرض في النموذج — عدّل ثم احفظ',
            'admin.lst.formNew': 'إضافة عرض جديد',
            'admin.lst.formEdit': 'تعديل عرض',
            'admin.lst.formHint': 'املأ الحقول ثم اضغط «حفظ العرض»',
            'admin.lst.sectionBasic': 'المعلومات الأساسية',
            'admin.lst.sectionPrice': 'التسعير والمخزون',
            'admin.lst.sectionPlace': 'المكان',
            'admin.lst.sectionImage': 'صورة العرض',
            'admin.lst.type': 'نوع العرض',
            'admin.lst.typeHint': 'فعالية، مطعم، أو رياضة',
            'admin.lst.typeEvent': 'فعالية',
            'admin.lst.typeRestaurant': 'مطعم / مقهى',
            'admin.lst.typeSport': 'رياضة',
            'admin.lst.title': 'اسم العرض',
            'admin.lst.titlePh': 'مثال: سيكس فلاجز القدية',
            'admin.lst.slug': 'الرابط المختصر (slug)',
            'admin.lst.slugPh': 'six-flags-qiddiya',
            'admin.lst.slugHint': 'يُولَّد تلقائياً من الاسم إن تركته فارغاً',
            'admin.lst.desc': 'وصف العرض',
            'admin.lst.descPh': 'اكتب وصفاً يظهر للزوار...',
            'admin.lst.price': 'السعر (ريال)',
            'admin.lst.stock': 'عدد التذاكر',
            'admin.lst.category': 'التصنيف',
            'admin.lst.categoryPh': 'مثال: مدن ترفيهية',
            'admin.lst.venue': 'الموقع / المدينة',
            'admin.lst.venuePh': 'مثال: القدية — الرياض',
            'admin.lst.pickImage': 'اختيار صورة من الجهاز',
            'admin.lst.uploading': 'جاري الرفع...',
            'admin.lst.imagePath': 'مسار الصورة (رابط أو مجلد محلي)',
            'admin.lst.imagePh': 'event/5.jpeg',
            'admin.lst.imageHint': 'مثال: event/5.jpeg أو رابط Supabase بعد الرفع',
            'admin.lst.noImage': 'لا توجد صورة',
            'admin.lst.published': 'نشر العرض على الموقع (يظهر للزوار)',
            'admin.lst.publishedShort': 'منشور',
            'admin.lst.saveBtn': 'حفظ العرض',
            'admin.lst.listTitle': 'العروض الحالية',
            'admin.lst.thImage': 'الصورة',
            'admin.lst.errTitle': 'أدخل اسم العرض',
            'admin.lst.imageOk': 'تم رفع الصورة بنجاح',
            'admin.lst.imageLocal': 'تم حفظ المسار المحلي — ضع الملف في مجلد الموقع',
            'admin.lst.imagePickFirst': 'اختر صورة أولاً',
            'admin.lst.imageFail': 'فشل رفع الصورة',
            'admin.bookings.title': 'جميع الحجوزات',
            'admin.bookings.user':  'المستخدم',
            'admin.bookings.remove': 'حذف من السجل',
            'admin.bookings.confirmRemove': 'حذف هذا الحجز الملغى من القائمة؟',
            'admin.bookings.removed': 'تم حذف الحجز',
            'admin.col.actions':    'إجراءات',
            'admin.stats.title':    'الإيرادات والأكثر حجزاً',
            'admin.stats.revenue':  'إجمالي المبيعات (المؤكدة)',
            'admin.stats.bookings': 'عدد الحجوزات المؤكدة',
            'admin.stats.top':      'أكثر العروض حجزاً'
        }
    };

    var current = (function () {
        try { return localStorage.getItem('xplore_lang') || 'en'; } catch (e) { return 'en'; }
    })();

    function t(key) {
        var dict = T[current] || T.en;
        return (dict[key] !== undefined ? dict[key] : T.en[key]) || key;
    }

    function applyLang(lang) {
        current = lang;
        try { localStorage.setItem('xplore_lang', lang); } catch (e) {}

        var html = document.documentElement;
        html.setAttribute('lang', lang);
        html.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');
        document.body.style.fontFamily = lang === 'ar'
            ? "'Cairo', 'Poppins', sans-serif"
            : "'Poppins', sans-serif";

        /* Text content */
        document.querySelectorAll('[data-i18n]').forEach(function (el) {
            el.textContent = t(el.getAttribute('data-i18n'));
        });

        /* Inner HTML — for elements containing <span>, <br> etc. */
        document.querySelectorAll('[data-i18n-html]').forEach(function (el) {
            el.innerHTML = t(el.getAttribute('data-i18n-html'));
        });

        /* Input placeholders */
        document.querySelectorAll('[data-i18n-ph]').forEach(function (el) {
            el.placeholder = t(el.getAttribute('data-i18n-ph'));
        });

        /* Page title */
        var titleKey = document.body.getAttribute('data-page-title');
        if (titleKey) { document.title = t(titleKey); }

        /* Language toggle button — update only the span, preserve the globe icon */
        var btn = document.getElementById('langToggle');
        if (btn) {
            var ls = btn.querySelector('[data-i18n="lang.switch"]');
            if (ls) { ls.textContent = t('lang.switch'); }
            else { btn.textContent = t('lang.switch'); }
        }

        try {
            document.dispatchEvent(new CustomEvent('xplore:langchange', { detail: { lang: lang } }));
        } catch (e) {}
    }

    function init() { applyLang(current); }

    function toggle() { applyLang(current === 'en' ? 'ar' : 'en'); }

    return {
        init: init,
        toggle: toggle,
        t: t,
        apply: applyLang,
        current: function () { return current; }
    };
})();
